### ISSUE TITLE
Usunięcie zasady "10s = udane"

### ISSUE THREAD

**Issue by Wallens** [Mrucznik/Mrucznik-Docs#14]
**Opis zmiany.**
Obecnie mamy:
https://github.com/Mrucznik/Mrucznik-Docs/blob/d25c204a2b33d1584625def82bd730a86ad5ffe7/lista-zasad.html#L106

Proponuję zmienić na:

> Nasz serwer jest serwerem Role Play a więc wszyscy są zobowiązani do odgrywania akcji. Jeżeli ktoś napisze akcję skierowaną do ciebie, masz obowiązek zareagować (pozytywnie lub negatywnie). Uciekanie od akcji, opóźnianie lub niereagowanie na nią, czy też opuszczanie serwera podczas jej trwania jest traktowanie jako nieodgrywanie i grozi za to kara. Jeżeli z jakiegoś powodu nie możesz lub nie chcesz odgrywać akcji - zawołaj administratora lub dogadaj się z graczem na czacie OOC. Jeżeli gracz, na którym wykonujesz akcję, nie odpowiada na nią przez co najmniej 20 sekund, traktowane jest to jako unikanie akcji RP i należy zgłosić to do administratora.

**Dlaczego uważasz, że zmiana jest potrzebna.**
Zasada "10s = udane" wydaje się problematyczna, gdyż mogę przykładowo podejść na mieście do losowego człowieka, odegrać akcję okradania go ze wszystkiego i liczyć na to, że będzie AFK/nie zdąży zareagować na akcję w ciągu 10 sekund. I wówczas, w teorii, powinniśmy otrzymać majątek, jaki przy sobie posiada.

**Comment by Akaexus** [comment]
Jak dodać Issue z odniesieniem do konkretnej linii pliku LKiZ:
![instrukcja](https://i.imgur.com/MVgnOki.png)

1. Wejdź w plik LKiZ
2. Kliknij na numer oznaczający linijkę
3. Jeżeli chcesz zaznaczyć więcej niż 1 linijkę tekstu, klikaj na numery z przytrzymanym klawiszem SHIFT
4. Kliknij na guzik z 3 kropkami
5. Kliknijna "Open new Issue"
6. Dalej postępuj tak jak w przypadku tworzenia nowego issue

**Comment by Mrucznik** [comment]
Racja, 10s = udane może prowadzić do nadużyć.

**Comment by 0Verte** [comment]
Będziemy to zmieniać zgodnie z propozycją.

**Comment by Mrucznik** [comment]
Zrobione.
