### ISSUE TITLE
Modyfikacja ograniczeń dotyczących nicków

### ISSUE THREAD

**Issue by Wallens** [Mrucznik/Mrucznik-Docs#15]
**Opis zmiany.**

Obecnie mamy:
https://github.com/Mrucznik/Mrucznik-Docs/blob/d25c204a2b33d1584625def82bd730a86ad5ffe7/lista-zasad.html#L114

Zmienić na:

> Aby zachować realność, zgodność z rzeczywistym światem i klimat rozgrywki Role Play, na naszym serwerze trzeba posiadać odpowiedni nick. Tak jak w prawdziwym świecie nasza postać musi mieć imię oraz nazwisko, więc nicki muszą mieć formę "Imie_Nazwisko". Dopuszcza się 2-członowe imiona oraz nazwiska (np. Robert_Adam_Szczota, James_Deco_Morreno). Nie można posiadać również nicków o charakterze wulgarnym. Obowiązuje zakaz używania nicków osób sławnych/historycznych, lub łudząco do nich podobnych (Celebrity Name - CN). Zabronione są także nazwy postaci które w sposób oczywisty budzą negatywne skojarzenia lub nadmierną śmieszność oraz wywołują skargi (raporty), przy czym musi wynikać powiązanie między imieniem i nazwiskiem. Zabronione są również nicki łudząco przypominające nicki członków administracji.

Zmiany, jakie zaszły:

- usuwamy z przykładów dwuczłonowych nicków "Kim_Dzong_Un", gdyż jest to nick niepoprawny ze względu na CN
- dopisujemy, że za CN są uznawane również nicki łudząco podobne do osób sławnych/historycznych. Kwestia tego, że obecnie można sobie ustawić nick Donald_Tramp i właściwie nie złamiemy LKiZ
- dodajemy zakaz ustawiania nicków łudząco podobnych do nicków administracji. Ten zakaz jest na pewno potrzebny, ale można jeszcze pomyśleć o rozszerzeniu go na innych graczy

**Dlaczego uważasz, że zmiana jest potrzebna.**
Podawanie niepoprawnego nicku jako przykładu chyba nie wymaga wyjaśnień. Drobne zmiany w nicku osoby sławnej również powinny być zabronione, bo i tak budzą one skojarzenia z tymi osobami. No i podszywanie się pod administrację również musi być zabronione, bo można to wykorzystać do zdobycia informacji niejawnych.

**Comment by Mrucznik** [comment]
Blocki z powodu nicków łudząco podobne do graczy/administracji powinny być rozpatrywane z wniosku gracza, tak samo dodałbym zakaz używania danych osobowych innych graczy jako nicków.

**Comment by Shankq** [comment]
**Zmieniłbym jeszcze tę definicję:**

Zabronione są także nazwy postaci które w sposób oczywisty budzą negatywne skojarzenia lub nadmierną śmieszność oraz wywołują skargi (raporty), przy czym musi wynikać powiązanie między imieniem i nazwiskiem.

**Na następującą:**
Zabronione są także nazwy postaci które w sposób oczywisty budzą negatywne skojarzenia lub nadmierną śmieszność oraz wywołują skargi (raporty).

**Comment by Mrucznik** [comment]
Zmieniono definicje na:
Aby nick był poprawny, muszą zostać spełnione następujące zasady:
* Nick musi być w formie Imie_Nazwisko
* Nie może być wulgarny
* Nie może budzić negatywnych lub wulgarnych skojarzeń
* Nie może być celowo oparty o prawdziwe dane osobowe któregoś z graczy
* Nie może być nadmiernie śmieszny
* Nie może wprowadzać w błąd (podszywanie itd.)

Przykład Kim_Dzon_Un zmieniony na Janusz_Koran_Mekka i Marcepan_von_Marks.
