### ISSUE TITLE
Nowy dopisek przy definicji DM

### ISSUE THREAD

**Issue by Wallens** [Mrucznik/Mrucznik-Docs#16]
**Opis zmiany.**

Obecnie mamy:
https://github.com/Mrucznik/Mrucznik-Docs/blob/d25c204a2b33d1584625def82bd730a86ad5ffe7/lista-zasad.html#L119

Zmienić na:
`<span style="color: #ff0000">Deathmatch (<strong>DM</strong>)</span> - Zabójstwo/uszkodzenie gracza/mienia bez wyraźnego i adekwatnego do sytuacji powodu IC. Przy ocenie adekwatności powodu należy mieć na uwadze rys fabularny serwera, przedstawiony na początku Listy Zasad.`

**Dlaczego uważasz, że zmiana jest potrzebna.**
Sytuacja panująca na serwerze odbiega znacznie od sytuacji ze świata OOC. Część administratorów uzasadnia jednak kary za DM2 pytaniami "Czy w realnym życiu też zacząłbyś strzelać?". Należy pamiętać, że ze względu na rys fabularny serwera, mamy zdecydowanie większe przyzwolenie na użycie broni i atak.

**Comment by Mrucznik** [comment]
Takie doprecyzowanie może być pomocne, jednak myślę, że jest zbyt obszerne tekstowo i jest przydatna tylko administratorom. Bardziej pasowałoby to do jakiegoś rozszerzonego tekstu obejmującego przykładowe sytuacje i interpretacje LKiZ jak i opisy jakichś precedensów.

Zastanawiam się, czy nie dodać do listy kar i zasad takiego właśnie dokumentu, który obszerniej opisywał by jakieś pojęcia i zawierał precedensy. Trzeba pamiętać, że LKiZ musi być krótka i zwięzła, aby nie tylko administratorzy ją czytali, ale też gracze.

**Comment by Mrucznik** [comment]
#39 dodałem issue o tym, o czym pisałem wyżej

**Comment by Mrucznik** [comment]
Została wprowadzona lista precedensów opisująca dokładniej co i jak, jednak możliwe, że stworzymy w przyszłości też jakieś dokładniejsze opisy.

**Comment by 0Verte** [comment]
Myślę, ze warto dodać taki dopisek aby zwrócić na to uwagę adminom w w przyszłości rozbudować kartę o przykłady i precedensy

**Comment by Mrucznik** [comment]
Dodano 2 zasady:


Nazwa | Typ zasady | Opis
-- | -- | --
Zasada adekwatności reakcji | Rozgrywka | Na każdą akcję gracza możemy odpowiedzieć reakcją, lecz pamiętajmy, że każda reakcja musi być adekwatna do jej przyczyny. Szczególną uwagę trzeba zwracać na akcje, które są akcjami agresywnymi skierowanymi do innego gracza. Aby ułatwić definiowanie, kiedy gracz postąpił zbyt agresywnie i jego reakcja zalicza się do DM'u, zostały przyjęte następujące zasady:Na atak werbalny lub atak na mienie gracza może zareagować przemocą fizyczną z użyciem broni białej (oprócz piły), uprzednio formułując komunikat skierowany do atakującego (komunikat typu: "ta zniewaga krwi wymaga" itd.)Na umyślny atak fizyczny z użyciem dowolnej broni, gracz może zareagować bronią palną.Nie wyczerpuje to wszystkich sytuacji, w których gracz może dopuścić się legalnego ataku bronią palną, a jedynie definiuje dozwolone reakcje dla tych najczęstszych.
Zasada odgrywania swojej postaci zgodnie z rolą | Rozgrywka | Nasze postacie muszą wpasowywać się w role, które określone są skryptem. Każda rola obostrzona jest następującymi ograniczeniami.Cywil (posiada legalną prace lub należy do legalnej organizacji) - nie może atakować za pomocą broni palnej innych osób bez uprzednich ataków werbalnych/fizycznych/mienia od strony innych graczy.Cywil przestępca (posiada pracę przestępczą) - nie może atakować za pomocą broni palnej funkcjonariuszy bez uprzednich prób zatrzymania przez takowych.Gangster (należy do organizacji przestępczej) - może atakować z broni palnej dowolne wybrane grupy osób, do których wrogie nastawienie wynika z tła fabularnego organizacji.Funkcjonariusz (należy do frakcji porządkowej + jest na służbie) - nie może atakować bronią palną osób, które nie są poszukiwane.Broń palna to wszelka broń, którą bezpodstawny atak zaliczany jest jako DM2.
