### ISSUE TITLE
Usunięcie pojęcia Noob Kill

### ISSUE THREAD

**Issue by Wallens** [Mrucznik/Mrucznik-Docs#17]
**Opis zmiany.**

Trzeba usunąć poniższą linijkę:
https://github.com/Mrucznik/Mrucznik-Docs/blob/d25c204a2b33d1584625def82bd730a86ad5ffe7/lista-zasad.html#L132

**Dlaczego uważasz, że zmiana jest potrzebna.**
W ciągu tylu lat gry na Mruczniku, nie wiem, czy chociaż 5 razy spotkałem się z tym, aby jakiś administrator nadał karę za Noob Kill. Według mnie pozostałe rodzaje DMu w zupełności wystarczą w każdej sytuacji. Dodatkowo na ogół bardzo ciężko jest udowodnić komuś, że dokonał DMu ze względu na nieznajomość zasad RP.

**Comment by Mrucznik** [comment]
Racja.

**Comment by Mrucznik** [comment]
Odrzucam.
Aby ta zasada była częściej używana, zostanie zmieniona jej definicja na:
_Zabicie gracza z powodu nieznajomości zasad RP lub niskiej jakości odgrywanych przez niego akcji._
