### ISSUE TITLE
Dodanie dopisku przy rzeczach posiadanych skryptowo

### ISSUE THREAD

**Issue by Wallens** [Mrucznik/Mrucznik-Docs#18]
**Opis zmiany.**

Obecnie mamy:
https://github.com/Mrucznik/Mrucznik-Docs/blob/d25c204a2b33d1584625def82bd730a86ad5ffe7/lista-zasad.html#L175

Proponuję dodać na koniec zdanie:
`<li>Każdą rzecz, którą gracz posiada w (<strong>/stat(s)</strong>tykach) posiada również ze sobą, jeżeli gracz posiada SS z przechowywania rzeczy w innym miejscu niż <strong>/stats </strong>(np w domu, aucie itd) ma obowiązek przedstawić dowody, ale uwaga - maksymalnie daną rzecz możemy przechowywać mając dowody to 2 dni od czasu stworzenia dowodów (<span style="color: #a52a2a">SS bez /czas jest nie ważny</span>).</li> Należy mieć na uwadze, że ukrycie licencji (mowa tu o dokumentach spod komendy /licencje) nie chroni nas przed unieważnieniem jej przez frakcję porządkową, ponieważ są one unieważniane elektronicznie.`

**Dlaczego uważasz, że zmiana jest potrzebna.**
Były i wciąż są kontrowersje wokół tego, czy schowana IC licencja może być unieważniona przez służby porządkowe. Na ogół administratorzy przyjmują, że tak, bo licencje są obecne w systemie i można je unieważnić elektronicznie, więc aby gracze nie mieli wątpliwości, potrzebny jest taki dopisek.

**Comment by Mrucznik** [comment]
Dodałbym to do #39

**Comment by 0Verte** [comment]
Zasada została skrócona, teraz to: <li>Każdą rzecz, którą gracz posiada w (<strong>/stat(s)</strong>tykach) posiada również ze sobą, jeżeli gracz posiada SS z przechowywania rzeczy w innym miejscu niż <strong>/stats.

Gracz nie ma już możliwości schować czegoś co posiada w statystykach. Jeżeli tak robi to jest to zagranie non-rp i należy je traktować jako nieważne.
