### ISSUE TITLE
Usunięcie zdania dot. wypłacania wygranych z kasyna

### ISSUE THREAD

**Issue by Wallens** [Mrucznik/Mrucznik-Docs#19]
**Opis zmiany.**

Należy usunąć linijkę:
https://github.com/Mrucznik/Mrucznik-Docs/blob/d25c204a2b33d1584625def82bd730a86ad5ffe7/lista-zasad.html#L178

**Dlaczego uważasz, że zmiana jest potrzebna.**
Gra w kasynie odbywa się teraz za pomocą skryptu i wygrana przekazywana jest automatycznie.

**Comment by Mrucznik** [comment]
ok

**Comment by Mrucznik** [comment]
Nope, jak ktoś nie gra automatycznie, np. używa ruletki, to ta zasada go chroni.
