### ISSUE TITLE
Nowy dopisek przy pojęciu AFK

### ISSUE THREAD

**Issue by Wallens** [Mrucznik/Mrucznik-Docs#20]
**Opis zmiany.**

Obecnie mamy:
https://github.com/Mrucznik/Mrucznik-Docs/blob/d25c204a2b33d1584625def82bd730a86ad5ffe7/lista-zasad.html#L192

Należy dopisać na koniec:
`<span style="color: #ff0000">Away From Keyboard (<strong>AFK</strong>) </span>- bycie nieaktywnym przez czas dłuższy niż 5 minut (odstęp po między nieaktywnościami minimum 3 minuty, inaczej czas nieaktywności się nie zeruje). Administrator ma prawo powstrzymać się od wymierzania kary, gdy gracz łamiący tę zasadę przebywa w AJ lub więzieniu (tylko w przypadku, gdy nikt nie odgrywa z nim żadnej akcji).`

**Dlaczego uważasz, że zmiana jest potrzebna.**
Przy obecnym wyglądzie więzienia oraz AJ nie ma sensu zmuszać gracza do gapienia się w kraty/barierkę.

**Comment by Mrucznik** [comment]
ok

**Comment by skMetinek** [comment]
Ja jestem na nie, AJ czy więzienie to jest kara a nie - dostaje kare za DM2 20min przykładowo idę sobie afka walne zjem coś i wracam będąc po AJ i tak dzieje się ciągle na serwerze dlatego każdy ma gdzieś że dostanie kare i od afczy sobie cały sens AJ lub więzienia

**Comment by Mrucznik** [comment]
Dodano do wykluczeń:
* AFK w więzieniu, gdy nikt nie odgrywa z nami żadnej akcji
