### ISSUE TITLE
Usunięcie przykładu zachowania, które nie jest uznawane za BU

### ISSUE THREAD

**Issue by Wallens** [Mrucznik/Mrucznik-Docs#21]
**Opis zmiany.**

Mamy w LKiZ przykład zachowania, które nie jest uznawane za BU, należy poniższą linijkę usunąć:
https://github.com/Mrucznik/Mrucznik-Docs/blob/d25c204a2b33d1584625def82bd730a86ad5ffe7/lista-zasad.html#L240

**Dlaczego uważasz, że zmiana jest potrzebna.**
O ile wiem, pojazdy te zostały usunięte z LV, więc zapisek jest zbędny.

**Comment by Mrucznik** [comment]
k

**Comment by Mrucznik** [comment]
Akceptowane, zmiana zostanie uwzględniona w nowej LKiZ.
