### ISSUE TITLE
Zmiana kosmetyczna przykładów zachowań uznawanych za BU

### ISSUE THREAD

**Issue by Wallens** [Mrucznik/Mrucznik-Docs#22]
**Opis zmiany.**

Mamy obecnie:
`<li>BU szybsze pływanie, bieganie</li>
          <li>BU szlabany pod komi</li>`

Proponuję zmienić na:
`<li>Szybsze pływanie/bieganie</li>
          <li>Przeskakiwanie pojazdem (również motorem) nad szlabanami</li>`

**Dlaczego uważasz, że zmiana jest potrzebna.**
Po pierwsze, skoro są to przykłady zachowań, które **nie są** BU, to należy usunąć z nich słowo BU, bo inaczej są to oksymorony. Drugi przykład przeredagowany na znacznie bardziej czytelny, aby było wiadomo, o co w nim chodzi.

**Comment by Mrucznik** [comment]
#39 powiązane

**Comment by Mrucznik** [comment]
potrzeba przepisać interpretacje BU do pliku z interpretacjami zasad lkiz

**Comment by Shankq** [comment]
Proponuję usunięcie spisu rzeczy uznawanych za BU i danie @ możliwości własnej interpretacji tego, co podchodzi pod BU, bo co chwila ludzie wynajdują jakieś nowe.

**Comment by Wallens** [comment]
Z całym szacunkiem, ale chociażby na podstawie Twoich działań mogę stwierdzić, że byłby to kiepski pomysł. Twierdziłeś, że samo noszenie kamizelki (przez komendę /dopasuj kamizelka, która jest dostępna **po zakupieniu** kamizelki u ochroniarza) to BU, bo na kamizelce jest napis "POLICE", więc gracz spoza LSPD nie może takiej posiadać.

**Comment by Mrucznik** [comment]
> bo na kamizelce jest napis "POLICE", więc gracz spoza LSPD nie może takiej posiadać.

xDDD close., zmienione
