### ISSUE TITLE
Dodanie nowych zachowań uznawanych za szkodzenie serwerowi

### ISSUE THREAD

**Issue by Wallens** [Mrucznik/Mrucznik-Docs#23]
**Opis zmiany.**

Mamy listę zachowań:
https://github.com/Mrucznik/Mrucznik-Docs/blob/d25c204a2b33d1584625def82bd730a86ad5ffe7/lista-zasad.html#L252-L255

Dodajemy do niej dwa kolejne:
`<li>Zastawiwanie przejazdu pociągiem</li>
            <li>Crashowanie serwera</li>
            <li>Holowanie czołgu, samolotów, helikopterów w celu dezorganizacji rozgrywki</li>
            <li>Spychanie helikopterów LSPD z dachu</li>
            <li>Blokowanie wjazdów/przejazdów poprzez zaparkowanie tam pojazdu i respawnowanie go po tym, jak zostanie stamtąd usunięty</li>
            <li>Blokowanie ruchliwej drogi barierkami bez adekwatnego powodu IC, jedynie w celu utrudnienia przejazdu innym graczom</li>`

**Dlaczego uważasz, że zmiana jest potrzebna.**
Usunąłem dopisek, że spychanie helikopterów musi odbywać się na dachu LSPD. Inne frakcje też mają helikoptery na dachach (np. FBI), więc trzeba rozszerzyć to zdanie.
Dwa nowe zachowania uznawane za szkodzenie serwerowi - pierwsze, gdy ktoś zaparkuje auto w jakimś wjeździe (np. Pay'N'Spray, co miało już miejsce) i nieustannie je respawnuje (gdy zostanie odholowane/przesunięte). Druga sytuacja, to gdy ktoś blokuje barierkami ruchliwą ulicę tylko po to, aby była zablokowana.

**Comment by WayneMRP** [comment]
Administrator ma prawo nadać kare jeśli uzna pewne zachowania za szkodzenie mimo, że nie jest wymienione poniżej - proszę dodać taki zapis.

**Comment by Wallens** [comment]
Byłbym za, jednak obawiam się, że niektórzy administratorzy mogliby podciągać pod to naprawdę błahe powody, lub traktowaliby to jako jakąś alternatywę massiv/nagminnego DMu.  Można byłoby dodać taki zapis i zobaczyć, jak się sprawdzi - jeśli będzie używany rzadko, w wyjątkowych i uzasadnionych sytuacjach, to nie mam nic przeciwko.

**Comment by Mrucznik** [comment]
Szkodzenie serwerowi faktycznie przydałoby się jakoś zmienić i stworzyć definicję, która w miarę wyczerpywała by temat lub stworzyć jakiś system do zgłaszania nowych sytuacji, które można uznać za szkodzenie serwerowi.

**Comment by Mrucznik** [comment]
Redefiniujmy to pojęcie, założyłem nowego issue. #38

**Comment by Mrucznik** [comment]
Duplicate of #38
