### ISSUE TITLE
Nowe zasady chatów

### ISSUE THREAD

**Issue by Wallens** [Mrucznik/Mrucznik-Docs#24]
**Opis zmiany.**

Mamy obecnie:
https://github.com/Mrucznik/Mrucznik-Docs/blob/d25c204a2b33d1584625def82bd730a86ad5ffe7/lista-zasad.html#L278-L348

Proponuję zmienić na:
https://pastebin.com/znaBvwQx

**Dlaczego uważasz, że zmiana jest potrzebna.**
Dodajemy oznaczenia [G] oraz [M], dzięki którym nie będzie wątpliwości, czy chat jest globalny/lokalny i mówiony/pisany. Jest to niestety konieczne, bo widziałem administratorów, którzy uznawali /opis albo /m za chaty globalne. Rozbudowujemy punkt dot. chatu /m, bo dało się go wykorzystywać w denerwujący dla innych graczy sposób.

**Comment by Mrucznik** [comment]
później przyjrzę się dokładniej zmianom, ale oznaczam jako todo

**Comment by Mrucznik** [comment]
Dodane oznaczenia [G] i [M]
