### ISSUE TITLE
Zmiana definicji reklamowania

### ISSUE THREAD

**Issue by Wallens** [Mrucznik/Mrucznik-Docs#25]
**Opis zmiany.**

Obecnie mamy:
https://github.com/Mrucznik/Mrucznik-Docs/blob/d25c204a2b33d1584625def82bd730a86ad5ffe7/lista-zasad.html#L364

Proponuję zmienić na:
`<span style="color: #ff0000">Reklamowanie </span>- zachęcanie innych graczy do gry na innym serwerze RolePlay oraz wysyłanie linków do stron innych serwerów RolePlay.`

**Dlaczego uważasz, że zmiana jest potrzebna.**
Nie oszukujmy się, prawie każdy gracz wie o istnieniu innych, konkurencyjnych serwerów na SA:MPie. Za samo napisanie nazwy jakiegoś serwera według mnie nie powinno się karać.

**Comment by Mrucznik** [comment]
OK

**Comment by Mrucznik** [comment]
Zmiana definicji na: Zachęcanie innych graczy do gry na innym serwerze RP lub wysyłanie linków do stron innych serwerów RP lub pisanie ich nazw.
