### ISSUE TITLE
Zmiana definicji sprzedaży konta

### ISSUE THREAD

**Issue by Wallens** [Mrucznik/Mrucznik-Docs#26]
**Opis zmiany.**

Obecnie mamy:
https://github.com/Mrucznik/Mrucznik-Docs/blob/d25c204a2b33d1584625def82bd730a86ad5ffe7/lista-zasad.html#L260

Proponuję zmienić na:
` <span style="color: #ff0000">Handel kontem</span> - sprzedaż/kupno/udostępnianie konta lub rzeczy do konta przypisanej za korzyści OOC. Konta są własnością Mrucznik-RP i nie zezwala się na sprzedawanie/kupowanie ich lub ich części. Samo złożenie oferty sprzedaży/udostępnienia/kupna konta uznawane jest za złamanie tej zasady.`

W związku z tym zagadnieniem należałoby również zmienić nazwę w Liście Kar z "Sprzedaż kont" na "Handel kontem".

**Dlaczego uważasz, że zmiana jest potrzebna.**
Obecna treść LKiZ nie zabrania kupowania kont. Dodatkowo, aby była jasność, samo złożenie oferty jest już traktowane jako handel.

**Comment by sktoms** [comment]
Ta, byłoby o wiele lepiej

**Comment by Mrucznik** [comment]
ok

**Comment by KobaltowyEryk** [comment]
Nie zgodzę się z tym złożeniem oferty, sprzedaż konta jest poważnym zarzutem i żeby za nią karać, powinno się mieć twarde dowody, a nie tylko informacje o sprzedaży.

**Comment by Mrucznik** [comment]
Akceptowane, zmiana zostanie uwzględniona w nowej LKiZ.

Nowa definicja
> sprzedaż/kupno/udostępnianie konta lub rzeczy do konta przypisanej za korzyści OOC. Konta są własnością Mrucznik-RP i nie zezwala się na sprzedawanie/kupowanie ich lub ich części. Samo złożenie oferty sprzedaży/udostępnienia/kupna konta może być uznane za złamanie tej zasady.
