### ISSUE TITLE
Modyfikacja zasady zwiększania kar ze względu na skargę na forum

### ISSUE THREAD

**Issue by Wallens** [Mrucznik/Mrucznik-Docs#28]
**Opis zmiany.**

Mamy obecnie:
https://github.com/Mrucznik/Mrucznik-Docs/blob/d25c204a2b33d1584625def82bd730a86ad5ffe7/lista-kar.html#L77

Proponuję zmienić na:
`<li>Jeżeli gracz złożył skargę na forum, stopień kary może zostać podniesiony o 1 poziom lub wartość może być zwiększona x2.</li>`

**Dlaczego uważasz, że zmiana jest potrzebna.**
Możliwość zwiększenia wartości kary x2 powinna dotyczyć każdej kary, nie tylko kar specjalnych. Obecnie rozpatrując skargi, mogę za DM2 nadać albo do 30 minut AJ albo warna. Są często sytuacje, że 30 minut AJ to za mało, a warn jest zbyt surową karą. Możliwość dłuższego AJ byłaby najlepszym wyjściem.

**Comment by Mrucznik** [comment]
ok

**Comment by Mrucznik** [comment]
Wpis zmieniony na:
Jeżeli gracz złożył skargę na forum, stopień kary może zostać podniesiony o 1 poziom (np. z kary średniej na karę ciężką) lub wartość kary może być pomnożona przez 2.
