### ISSUE TITLE
Zabawa warningami

### ISSUE THREAD

**Issue by WayneMRP** [Mrucznik/Mrucznik-Docs#30]
**Opis zmiany.**
Celowe i nagminne wykorzystywanie warningów administracyjnych.

**Dlaczego uważasz, że zmiana jest potrzebna.**
Utrudnienia w grze.

**Comment by Mrucznik** [comment]
mógłbym prosić o przykłady takich sytuacji?

**Comment by Mrucznik** [comment]
Zostanie dodany odpowiedni przykład w definicji spamu.
