### ISSUE TITLE
Kradzież tożsamości OOC

### ISSUE THREAD

**Issue by WayneMRP** [Mrucznik/Mrucznik-Docs#31]
**Opis zmiany.**
Dodać do LKIZ karę ban'a za kradzież tożsamości OOC.

**Dlaczego uważasz, że zmiana jest potrzebna.**
Nie może być zgody by dane, któregokolwiek z naszych graczy wyciekały w ten czy inny sposób dlatego ta kara jest tak potrzebna, nie można ustawiać nicków z tożsamości gracza, którego znamy.

**Comment by Wallens** [comment]
W jaki sposób chcesz sprawdzać autentyczność tych danych?

**Comment by Mrucznik** [comment]
Takie sytuacje dzieją się zazwyczaj poza naszym serwisem, natomiast to, że ktoś publikuje swoje dane osobwe lub zostaje wystalkowany to jest jego problem i nijak ma się do serwera.

**Comment by WayneMRP** [comment]
Jeśli gracze znają swoje dane OOC, to przy kłótni może jeden z nich wpaść na pomysł aby odgrywać dziwkę na nicku OOC tej osoby, to niezbyt smaczne zachowanie, powinniśmy chronić graczy, oczywiście takich kar będzie margines ale dobrze to mieć w LKIZ.

**Comment by Wallens** [comment]
Zapytam jeszcze raz - w jaki sposób sprawdzisz autentyczność tych danych? Przykładowo ustawię sobie nick Jan_Kowalski, drugi gracz zgłosi Ci, że wykorzystuję w ten sposób jego dane osobowe - jak stwierdzisz, że to faktycznie jego imię i nazwisko?

**Comment by Mrucznik** [comment]
Została zmieniona definicja złego nicku na:
Aby nick był poprawny, muszą zostać spełnione następujące zasady:
* Nick musi być w formie Imie_Nazwisko
* Nie może być wulgarny
* Nie może budzić negatywnych lub wulgarnych skojarzeń
* Nie może być celowo oparty o prawdziwe dane osobowe któregoś z graczy
* Nie może być nadmiernie śmieszny

Akceptowane, zmiana zostanie uwzględniona w nowej LKiZ.
