### ISSUE TITLE
Dodać karę za celowe zabicie się podczas akcji.

### ISSUE THREAD

**Issue by WayneMRP** [Mrucznik/Mrucznik-Docs#32]
**Opis zmiany.**
Podciągną celowe zabicie się podczas akcji RP do pojęcia ucieczka od akcji RP czy coś, żeby było objęte w LKIZ, iż celowe utonięcie/wybuch w aucie jest ucieczką od akcji RP.

**Dlaczego uważasz, że zmiana jest potrzebna.**
JW.

**Comment by Wallens** [comment]
Jak najbardziej potrzebne, bo jest to częste zachowanie uciekających - topią się gdzieś w wodzie albo spalają w ogniu.

**Comment by Mrucznik** [comment]
W czym problem? Czemu nie mogą zginąć?

**Comment by WayneMRP** [comment]
Mogą zginąć ale w takim razie muszą liczyć się z FCK.
Bo innej możliwości, służby porządkowe gonią gościa od x minut, albo co lepsze robią na niego śledztwo, już go mają zapuszkować a on wskakuje do wody i się topi, MK, koniec akcji.

Bezsens.

**Comment by Wallens** [comment]
Bo podczas akcji, szczególnie pościgów, jest to często narzędzie ucieczki od konsekwencji. Po zatrzymaniu zostałaby im zabrana broń, licencja, etc., dodatkowo trafiliby do paki. Natomiast jeśli się zabiją, to właściwie żadne konsekwencje ich nie dosięgną.

**Comment by Mrucznik** [comment]
Akceptowane, zmiana zostanie uwzględniona w nowej LKiZ.
