### ISSUE TITLE
Dodać do LKiZ karę za SK (spraykill)

### ISSUE THREAD

**Issue by WayneMRP** [Mrucznik/Mrucznik-Docs#33]
**Opis zmiany.**
Nie ma w LKIZ pojęcia SK a powinno być gdyż to nagminne na serwerze, ew. podciągnąć pod DM2.

**Dlaczego uważasz, że zmiana jest potrzebna.**
DM.

**Comment by Wallens** [comment]
Ja bym podciągnął to pod DM2. Jest to dość denerwujący sposób DMienia, więc karałbym mocniej niż za DM1, a też nie ma sensu tworzyć kolejnego podprzypadku DMu dla tej jednej rzeczy.

**Comment by Mrucznik** [comment]
Tak, trzeba dodać takie bronie jak spray i piła mechaniczna do definicji DMu 2

**Comment by Mrucznik** [comment]
Zabijanie sprejem zostanie podciągnięte do DM2 tak jak piła mechaniczna.
Akceptowane, zmiana zostanie uwzględniona w nowej LKiZ.
