### ISSUE TITLE
Dodanie kary do LKIZ za niepoprawne użycie /raport.

### ISSUE THREAD

**Issue by WayneMRP** [Mrucznik/Mrucznik-Docs#34]
**Opis zmiany.**
CMD /raport jest często przez graczy zaśmiecana różnymi pierdołami, które nie mają nic wspólnego z supportem. Należy dodać karę 1 stopnia za to zachowanie.

**Dlaczego uważasz, że zmiana jest potrzebna.**
Utrudnienia w adminowaniu. Spam.

**Comment by Wallens** [comment]
Przecież już teraz można za to nadawać karę 1 stopnia. Komenda "/report" jest wymieniona na liście chatów, a w karach pierwszego stopnia jest przewinienie "Używanie chatu niezgodnie z jego przeznaczeniem".

**Comment by Mrucznik** [comment]
No to trzeba dopisać to do interpretacji.

**Comment by 0Verte** [comment]
Definicja spamu została poszerzona o opisaną sytuację
