### ISSUE TITLE
Dodać notkę od LKIZ

### ISSUE THREAD

**Issue by WayneMRP** [Mrucznik/Mrucznik-Docs#35]
**Opis zmiany.**
Dodać notkę że po konsultacji z H@/vH@ można karać za przewinienia spoza LKiZ

**Dlaczego uważasz, że zmiana jest potrzebna.**
Gardner

**Comment by Mrucznik** [comment]
Dodałbym bardziej notkę, że można ukarać za coś z poza LKiZ, tylko wtedy powinien pójść wniosek na githubie o interpretacje tego i jeżeli przejdzie, to sytuacja zostaje dodana do tego dokumentu od interpretacji, a jeżeli nie to gracz jest uniewinniony.

**Comment by skMetinek** [comment]
Wtedy trzeba dopisać jakie mają być te kary spoza LKiZ no bo skąd mam wiedzieć czy to co nie zrobię będzie karane bo interpretuje to inaczej i w sumie jak się wypisze jakie to od razu można wpisać to do LKiZ bez przymusu pisania o tym, że H@ czy vH@ mogą nadawać sobie kary bo coś podchodzi pod coś a tamto pod tamto.

**Comment by Mrucznik** [comment]
Obecnie wykształciliśmy taką praktykę stosowania, że admin nadaje kontrowersyjną karę i uznana bądź odrzucona apelacja/skarga w tej sprawie staje się precedensem.

**Comment by Mrucznik** [comment]
Notatka odnośnie prezedensów zostanie dodana w nowej LKiZ.
