### ISSUE TITLE
Dodanie do LKiZ kary za DT

### ISSUE THREAD

**Issue by Jup1k** [Mrucznik/Mrucznik-Docs#36]
**Opis zmiany.**
Aktualnie strzelanie z okna pasażera(Drive Thru) jest karane jako DM2. Chciałbym, aby pojęcie te zostało dodane do Listy Kar i Zasad jako kara 4 stopnia - do 30min AJ/Warn.

**Dlaczego uważasz, że zmiana jest potrzebna.**
Ułatwienie dla administracji podczas karania graczy.

**Comment by Wallens** [comment]
Na czym polega to ułatwienie dla administracji? Że dacie większą karę i będziecie mieć z graczem spokój na dłużej? W czym takie strzelanie z okna jest gorsze od strzelania będąc pieszo?

**Comment by Mrucznik** [comment]
DT nie jest zakazane a zamieszczenie go w LKiZ mogłoby sugerować, że jest.
Robienie DM z pojazdu za pomocą DT to jedno i to samo i nie widzę powodu, by jakoś to rozróżniać.
