### ISSUE TITLE
Nowa definicja szkodzenia serwerowi

### ISSUE THREAD

**Issue by Mrucznik** [Mrucznik/Mrucznik-Docs#38]
**Opis zmiany.**
Obecnie szkodzenie serwerowi jest zbyt wąsko zdefiniowane, należy stworzyć nową definicję.

**Dlaczego uważasz, że zmiana jest potrzebna.**
Administratorzy nie mogą karać graczy za działania mające na celu szkodę dla serwera lub jego społeczności,

**Comment by Wallens** [comment]
Proponuję coś typu:

> Szkodzenie serwerowi - działania mające na celu zepsucie/utrudnienie rozgrywki dużej liczbie graczy, a także działania mające negatywny wpływ na wizerunek/działanie serwera.

Obecne zachowania uznawane za szkodzenie serwerowi dałoby się do powyższej definicji podpiąć, więc LKiZ troszkę by się odchudziło.

**Comment by Mrucznik** [comment]
Akceptowane, zmiana zostanie uwzględniona w nowej LKiZ.
