### ISSUE TITLE
Stworzenie dokumentu zawierającego doprecyzowanie pojęć oraz interpretacje LKiZ

### ISSUE THREAD

**Issue by Mrucznik** [Mrucznik/Mrucznik-Docs#39]
**Opis zmiany.**
Przydałby się dokument, w którym zamieszczalibyśmy doprecyzowanie interpretacyjne LKiZ jak i jakieś precedensy, które zostały ustalone na drodze skarg, apelacji czy zwykłego działania administracyjnego.
Potem mógłbym on posłużyć do przeredagowania LKiZ by była bardziej spójna i definicje pojęć uwzględniały zaistniałe interpretacje w ogóle.

**Dlaczego uważasz, że zmiana jest potrzebna.**
LKiZ powinna być krótka i zwięzła oraz powinno z niej wszystko wynikać, jednak doprecyzowania i interpretacje są przydatne, lecz powinny być zawarte w innym dokumencie, by nie zaciemniać rdzenia zasad.

**Comment by Wallens** [comment]
Proponowałem już coś takiego przy okazji tego tematu:
https://mrucznik-rp.pl/topic/69478-serwer-wprowadzenie-sta%C5%82ych-warto%C5%9Bci-kar-w-lkiz/
Niewątpliwie taki dokument przyniósłby sporo dobrego. Rozwiązuje nie tylko kwestie interpretacji, ale daje również administratorom jakiś wzorzec surowości przy wymierzaniu kar. Obecnie rozbieżność w karaniu wśród administracji jest bardzo duża. Jeden da dłuugi AJ/warna, a drugi w takiej samej sytuacji slapa/kicka.

**Comment by Mrucznik** [comment]
Został stworzony milestone, który dotyczy tego dokumentu.

**Comment by Mrucznik** [comment]
In progress.

**Comment by Mrucznik** [comment]
Została stworzona tabela z precedensami dla każdego podpunktu LKiZ oraz kolumny do przykładów dla każdego przewinienia, jednak nadal zastanawiam się nad podzieleniem LKiZ na definicje, które będą dosyć krótkie i zwięzłe, oraz opisy dla graczy jak i administracji.

**Comment by Mrucznik** [comment]
todo
