### ISSUE TITLE
Dodanie do czatu /cb oznaczenia [K]

### ISSUE THREAD

**Issue by Shankq** [Mrucznik/Mrucznik-Docs#40]
**Opis zmiany.**
Dodanie do czatu /cb oznaczenia [K], co spowoduje konieczność zachowania kultury na tym czacie.

**Dlaczego uważasz, że zmiana jest potrzebna.**
Obecnie czat /cb służy jedynie odwalaczom do wyzywania i obrażania innych. Na miejscu nowego gracza widząc to, co dzieje się na /cb od razu wpisałbym /q.
Zmiana spowoduje, że czat zacznie być używany zgodnie z jego przeznaczeniem, czyli do wymiany informacji pomiędzy kierowcami.

**Comment by Wallens** [comment]
Ale przecież nawet rzeczywistość pokazuje, że kultura na CB-radiu to często pojęcie abstrakcyjne. Wymóg kultury nie sprawi, że nagle ludzie zaczną na CB-radiu pytać "Mobilki, jak tam droga na Idlewood?". Argument z nowym graczem również nie ma zbytnio sensu, bo zanim taki nowy gracz zdobędzie pojazd i CB-radio, to prawdopodobnie odwiedzi najpierw bazę mechaników, gdzie dzieją się jeszcze gorsze rzeczy.

**Comment by Mrucznik** [comment]
J.w. Odrzucam.
