### ISSUE TITLE
Dodanie możliwości zabrania broni przez @ po otrzymaniu AJ z powodem DM2

### ISSUE THREAD

**Issue by Shankq** [Mrucznik/Mrucznik-Docs#41]
**Opis zmiany.**
Dodanie możliwości zabrania broni przez @ po otrzymaniu AJ z powodem DM2.

**Dlaczego uważasz, że zmiana jest potrzebna.**
W szczególnych przypadkach @ będzie miał prawo zabrać broń graczowi. Z pewnością zmniejszy to DM, bo gracze będą bali się utraty broni.

**Comment by Akaexus** [comment]
Należy sprecyzować czym jest szczególny przypadek.

**Comment by Shankq** [comment]
To już pozostawiłbym do dowolnej interpretacji. Jeśli admin uzna to za stosowne, to zabierze broń.

**Comment by KobaltowyEryk** [comment]
I własnie w taki sposób Shank, tworzą się dziury w LKiZ; 'zostawmy to do interpretacji'

**Comment by Mrucznik** [comment]
Zrealizowane przez Simeone - broń zabierana jest automatycznie po otrzymaniu kary z powodem DM2.
