### ISSUE TITLE
Regulacja dotycząca czatów frakcyjnych - globalnych.

### ISSUE THREAD

**Issue by WayneMRP** [Mrucznik/Mrucznik-Docs#42]
**Opis zmiany.**
Chciałbym aby został dodany zapis w LKIZ regulujący czaty frakcyjne tzw. globalne.

**Dlaczego uważasz, że zmiana jest potrzebna.**
Nie podoba mi się, kiedy to jakaś frakcja wręcz spamuje tym samym ogłoszeniem co minutę, uważam, że zaśmieca to czat, informacja nie jest potrzebna co 60 sekund przykładowo. Można napisać, iż można nadawać takie same ogłoszenie raz na 5 minut.

**Comment by KobaltowyEryk** [comment]
Wystarczy wprowadzić timer do komendy, warto jest go również wprowadzić do /ha i usunac z warningów @ info. o tym, kto nadał ha (jeśli jeszcze jest taka info)

**Comment by Mrucznik** [comment]
To jest zmiana skryptowa a nie zmiana do LKiZ. Dodałem odpowiednią kartę na trello.
