### ISSUE TITLE
Regulacja dotycząca jazdy na dachu auta z opisem.

### ISSUE THREAD

**Issue by Daglaas** [Mrucznik/Mrucznik-Docs#43]
**Opis zmiany.**
Uznanie jazdy na dachu z przykładowym opisem "w bagażniku" za NON-RP.
**Dlaczego uważasz, że zmiana jest potrzebna.**
Jazda z opisem jest nadużywana, często w ten sposób jeździ na dachu nadmierna liczba osób. Jest to nieestetyczne.

**Comment by Mrucznik** [comment]
Dodano nowy punkt LKiZ:
Jazda na dachu pojazdu bez uprzedniej akcji RP oraz animacji imitującej próbę utrzymania się na dachu (np. /animfinale 3) lub znajdowania się w bagażniku. Będąc na dachu w trakcie jazdy nie można się poruszać ani mieć wyciągniętej broni.
Wyłączenia:
* Nie obowiązuje, gdy gracz znajduje się na przestrzeni pojazdu, która umożliwia przewóz ludzi (np. paka pick-up'a)
