### ISSUE TITLE
Interpretacja BU

### ISSUE THREAD

**Issue by skMetinek** [Mrucznik/Mrucznik-Docs#44]
**Opis zmiany.**
<h4>Za BU są uznawane:</h4>
        <ul>
          <li>BU animacje (/animped, /animswat)</li>
          <li>C-BUG, Glitch (DE z okna)</li>

<h4>Za BU nie są uznawane</h4>
        <ul>
          <li>BU NRG w LV, Maverick w LV</li>
          <li>Tappowanie (naciskanie strzałki na motorze)</li>
          <li>BU szybsze pływanie, bieganie</li>
          <li>BU szlabany pod komi</li>

> Jeżeli jakiejś zasady tutaj nie ma, to znaczy, że nie obowiązuje. - wpis z LKIZ niedotyczący tylko BU

- Dopisanie do BU uznawane lub nie wpisu o tym, że są to tylko przykłady i nie tylko one mogą być brane pod uwagę

**Dlaczego uważasz, że zmiana jest potrzebna.**
Dla mnie te czynności mogą być źle interpretowane (i są nadal), ponieważ zgodnie z powyższym wpisem, że jeżeli czegoś nie ma to nie obowiązuje więc, dlaczego gracze są karani za czynności PODCHODZĄCE pod BU, które nie są wypisane? Mija się to kompletnie z celem, bo niby definicja BU wskazuje za co można być ukaranym, a przykłady poniżej zmniejszają pole manewru dla administracji ze względu na brak informacji o tym że są to tylko "pomocniki".
Proponowałbym dopisać jakiś mały wpis o tym, że są to tylko przykłady a nie czynności za które tylko można ukarać gracza lub po prostu dopisać wszystkie możliwe czynności które przyjdą do głowy.

**Comment by Mrucznik** [comment]
Zostało to wykonane, podzieliliśmy to na przykłady i wyłączenia.

**Comment by Mrucznik** [comment]
Akceptowane, zmiana zostanie uwzględniona w nowej LKiZ.
