### ISSUE TITLE
Poprawienie definicji/Inna interpretacja przekazywania majątku podczas kradzieży

### ISSUE THREAD

**Issue by skMetinek** [Mrucznik/Mrucznik-Docs#45]
**Opis zmiany.**
"<li>Podczas napadu/porwania gracz może oddać maksymalnie 1.000.000$(o ile taką posiada), bądź cały majątek według własnej woli, leczy pojęcia 'cały' nie oznacza pieniądze trzymane w banku."

-Poprawa oddania całego majątku podczas napadu lub porwania gracza i ew. kradzież na zgodną z definicją Przelewania majątku
-Poprawa literówki "leczy" na lecz (chyba taki był zamiar)
-Dodanie do pojęcia coś o przekazywaniu samochodów (lub usunięcie całego wpisu po "(o ile taką posiada)" )

**Dlaczego uważasz, że zmiana jest potrzebna.**
Według mnie, nie wiem jak jest teraz z tym, ale będzie nadużywane (lub jest), do przelewania majątku ponieważ zgodnie z definicją przelewania majątku nie można przekazać 20kk lub 50% majątku swojego, a zgodnie z tą powyżej, można oddać np. swojemu koledze który porwie nas z innymi swoimi kolegami przykładowo 100kk no bo widziałem, że ludzie chodzą, mając przy sobie po kilkanaście/set kk.
Tak przynajmniej ja to tak interpretuję.

**Comment by Mrucznik** [comment]
ja bym to w ogóle usunął bo jest to regulowane przez skrypt
obecnie jest ograniczenie /wezportfel do 1kk

**Comment by skMetinek** [comment]
Czyli można usunąć, bardziej chodzi mi o to tylko, że w takim przypadku jak jest aktualnie można oddać majątek bez kary przelewania go? Jedno przeczy niby drugiemu
Majątek jako dom, pojazdy itp

**Comment by Mrucznik** [comment]
Zmienione na:
Podczas napadu/porwania gracz może oddać maksymalnie 1.000.000$. Zakazuje się porywania w kasynach i poza nim po przegranej grze. Uwaga, napady/porwania mogą organizować tylko organizacje przestępcze.

**Comment by Mrucznik** [comment]
@0Verte
