### ISSUE TITLE
Dodanie [K] przy czatach

### ISSUE THREAD

**Issue by skMetinek** [Mrucznik/Mrucznik-Docs#46]
**Opis zmiany.**
Dodanie literki [K] oznaczającą przymus kultury na chacie, brak zachowania jej to niepoprawne użycie do:

<strong>chat /report</strong> - służy do przekazywania administracji informacji o osobie łamiącej LKiZ, o nieprawidłowości związanych ze skryptem lub działaniem sampa.
<strong>chat /zapytaj</strong> - pytania do administracji związanych z forum, rozgrywką na serwerze, zasadami role play.

**Dlaczego uważasz, że zmiana jest potrzebna.**
Zwiększy to przejrzystość chatów używanych przez gracz-administracja, oraz zapobiegnie to nadużywaniu braku kultury przez /report lub /zapytaj

**Comment by 0Verte** [comment]
Zrealizowano
