### ISSUE TITLE
Interpretacja definicji "Spamowanie"

### ISSUE THREAD

**Issue by skMetinek** [Mrucznik/Mrucznik-Docs#47]
**Opis zmiany.**
"<span style="color: #ff0000">Spamowanie </span>- kilkukrotne napisanie wiadomości o takim samym sensie merytorycznym w krótkim odstępie czasu."
zmienić:
   
-Wyrzucenie dopisku "sensie merytorycznym" ponieważ, według LKiZ mogę napisać przykładowo 20 zdań o innym sensie tzn. "Lubię piłkę", "Mrucznik jest fajny" itp. bo prowadzi to do nadużyć i nijak odnosi się do sytuacji.
-Dodanie od ilu wiadomości liczony jest Spam.
-Dodanie mniej więcej czasu w którym trzeba napisać do kogoś wiadomość, aby uniknąć kary (dla niektórych "krótko" to sekunda, a dla niektórych to dwie minuty - przykładowo)

**Dlaczego uważasz, że zmiana jest potrzebna.**
Definicja jest troszkę niejasna, i źle przez większość interpretowana - prowadzi to do nadużyć i tony późniejszych skarg,apelacji, bo ktoś źle zrozumiał definicje niż admin.

**Comment by Mrucznik** [comment]
Definicja zmieniona na:
_Wielokrotne wysyłanie niechcianych wiadomości krótkim w odstępie czasu._

**Comment by Mrucznik** [comment]
Akceptowane, zmiana zostanie uwzględniona w nowej LKiZ.
