### ISSUE TITLE
Poprawa definicji zasady ciągłości akcji?

### ISSUE THREAD

**Issue by skMetinek** [Mrucznik/Mrucznik-Docs#48]
**Opis zmiany.**
"<li>Admin ma prawo nadać karę tylko i wyłącznie za czynności przewidziane w LKiZ oraz o wysokości przewidzianej w LKiZ. Za jedną czynność niezgodną z LKiZ gracz może otrzymać tylko 1 karę.</li>"

-Zamiana na możliwość nadania po marcepanie kary za np. /q (warna) lub coś innego (Mrucznik możesz działać)

**Dlaczego uważasz, że zmiana jest potrzebna.**
Nie wiem jak to dokładnie wytłumaczyć, ale czynność ta jest zbyt mocno nadużywana przez graczy, którzy próbują uniknąć zabrania licencji lub dłuższej paki (DeMorgan 4k sekund na przykład)
Po prostu, według LKiZ i jego interpretacji gracz może otrzymać 1 karę, i po daniu przykładowo /q w kajdankach otrzymujemy automatycznie marcepana, szybkie wejście do gry powoduję nadanie jego i wtedy gracz nie otrzyma warna. Widziałem, że admini nadają po prostu warny za /q po marcepanie albo po wejściu gracza na serwer teleportują go, lub zdejmują nadając 0sekund AJ o nazwie kary: marcepan, co jest dla mnie śmieszne i prowadzi do masy skarg na adminów po tym. Nie wiem czy chodziło to o to, ale w LKiZ jest również zapis, o złamaniu akcji gdzie po złamaniu jej po prostu staje się nieważna.

**Comment by Mrucznik** [comment]
Zmieniono na:

> Admin ma prawo nadać karę tylko i wyłącznie za czynności przewidziane w LKiZ oraz o wysokości przewidzianej w LKiZ. Za jedną czynność niezgodną z LKiZ gracz może otrzymać tylko 1 karę, wyjątkiem jest sytuacja, w której kara została nadana przez skrypt. W takim przypadku administrator może anulować karę nadaną przez skrypt i nadać inną, przewidzianą przez LKiZ.

**Comment by Mrucznik** [comment]
albo takie coś

> Admin ma prawo nadać karę tylko i wyłącznie za czynności przewidziane w LKiZ oraz o wysokości przewidzianej w LKiZ. Za jedną czynność niezgodną z LKiZ gracz może otrzymać tylko 1 karę. Administrator może zmienić karę nadaną przez skrypt na inną, przewidzianą przez LKiZ.

które lepsze?

**Comment by skMetinek** [comment]
Lepsza druga wersja, bardziej zwięzła i prosta jak na chłopski rozum.

Mam tylko jedno pytanie, co w przypadku nadania kary od razu po czynie gracza, a w późniejszym czasie, jeżeli zostanie złożona skarga za ten czyn na gracza, to pozostaje normalnie tak jak w definicji, czy może warto byłoby zwiększyć karę poprzez dodatkowe AJ, albo podwojenie kary w przypadku gdy czyn był poważniejszy i kara została nadana zbyt mała?

**Comment by Mrucznik** [comment]
zmienione

**Comment by Mrucznik** [comment]
> Mam tylko jedno pytanie, co w przypadku nadania kary od razu po czynie gracza, a w późniejszym czasie, jeżeli zostanie złożona skarga za ten czyn na gracza, to pozostaje normalnie tak jak w definicji, czy może warto byłoby zwiększyć karę poprzez dodatkowe AJ, albo podwojenie kary w przypadku gdy czyn był poważniejszy i kara została nadana zbyt mała?

Kara może być zmieniona na drodze skargi na gracza lub na administratora, ale są to sytuacje wyjątkowe i administrator rozpatrujący skargę może takie coś zarządzić, najlepiej za porozumieniem z innym administratorem, który wcześniej nadał karę.
