### ISSUE TITLE
Definicja DM podczas eventu + Rodzaje

### ISSUE THREAD

**Issue by skMetinek** [Mrucznik/Mrucznik-Docs#49]
**Opis zmiany.**
 <strong>DM podczas eventu</strong> - DM podczas eventu lub masowego wydarzenia w którym uczestniczy więcej niż 10 osób mający na celu jego dezorganizację (nie wydarzeń polegających lub wymuszających wzajemną wymianą ognia)
Coś na:
<strong>DM podczas eventu</strong> - DM podczas eventu lub masowego wydarzenia mający na celu jego dezorganizację (Nie dotyczy: wydarzeń polegających na strzelaninie lub wymuszających wzajemną wymianę ognia)
+
<br /> Wyróżniamy 4 rodzaje DM'u:
Na:
<br /> Wyróżniamy 5 rodzajów DM'u:

**Dlaczego uważasz, że zmiana jest potrzebna.**
Definicja DM podczas eventu jest źle skonstruowana no bo tak szczerze - który admin będzie liczył czy na jakimś wydarzeniu np. 10 osób czy 9? A jeżeli 9 to już gracz po zabójstwie przykładowo 3 postaci dostanie tylko 20min AJ gdzie widoczna jest dezorganizacja eventu, ale nie było tych 9 osób, bo rozbiegli się albo nie przyjechali jeszcze ale event trwa. Wtedy mogę pisać skargę bo nie było wymaganej ilości osób żeby podciągnąć to pod DM na wydarzeniu?

Co do rodzajów - jest obecnie 5: DM1,DM2,DM podczas eventu,Noob Kill,Extremalny DM
Co do Noob Killa to polecałbym to usunąć bo na co to komu? Nie widziałem, żeby ktoś jeszcze za to karał xD

**Comment by Mrucznik** [comment]
Akceptowane, zmiana zostanie uwzględniona w nowej LKiZ.
