### ISSUE TITLE
Definicja NJ (Ninja Jacking)

### ISSUE THREAD

**Issue by skMetinek** [Mrucznik/Mrucznik-Docs#50]
**Opis zmiany.**
 <span style="color: #ff0000">Ninja Jacking (<strong>NJ</strong>)</span> - wyrzucanie gracza (kierowcy) z pojazdu bez wyraźnego powodu IC.
Coś na: 
<span style="color: #ff0000">Ninja Jacking (<strong>NJ</strong>)</span> - wyrzucanie gracza (kierowcy) z pojazdu bez odegrania akcji RP.
-Lub usunięcie tego wpisu całkowicie.
**Dlaczego uważasz, że zmiana jest potrzebna.**
Tak szczerze po co jest ta definicja jak przy każdym NJ mogę powiedzieć że powodem wyrzucenia gracza z pojazdu była kradzież jego auta? Wtedy cały sens przestaje mieć jakiekolwiek znaczenie i staje się bezużyteczny. Polecałbym zmianę tego na coś z akcją lub usunięcie całkowicie tego.
Zapraszam do dyskusji.

**Comment by Mrucznik** [comment]
Odrzucam, gracze mają możliwość skryptowego zablokowania wyrzucenia ich z pojazdu za pomocą /lock.
Auta do kradnięcia mają wyłamane zamki, bo jak sama nazwa wskazuje, zostały ukradzione.
Do kradzieży pojazdu gracza, gracz też musi mieć jakiś powód. Nie można kraść aut 'od tak', tak samo jak nie można kogoś zabić 'od tak'.

**Comment by skMetinek** [comment]
Nie można zamknąć pojazdów służbowych, tzn. tych z prac dorywczych lub publicznych w tym problem. Definicja nie jest potrzebna, większość zareaguje w taki sposób, że ostrzela kradnącego. Każdym powodem, może być brak auta, tylko nie jest to doprecyzowane poprzez "wyraźny" powód.
