### ISSUE TITLE
Zmiana w Zasadzie nadawania kar (LK)

### ISSUE THREAD

**Issue by skMetinek** [Mrucznik/Mrucznik-Docs#51]
**Opis zmiany.**
<li>Jeżeli czynność jest zabroniona w LKiZ, ale wykonywanie tej czynności przez gracza nikomu nie przeszkadza oraz jest akceptowana przez wszystkich obecnych graczy, admin może się powstrzymać od ukarania (tylko gdy jest pewien, że akcja nie przeszkadza żadnemu graczowi który ją widzi/słyszy).</li>
Coś na:
<li>Jeżeli czynność jest zabroniona w LKiZ, ale wykonywanie tej czynności przez gracza/graczów nikomu nie przeszkadza oraz jest akceptowana przez obecnych graczy (w miejscu akcji), admin ma obowiązek powstrzymać się od ukarania (tylko gdy jest pewien, że akcja nie przeszkadza żadnemu graczowi który ją widzi/słyszy).</li>

**Dlaczego uważasz, że zmiana jest potrzebna.**
Uważam, że bez sensu jest coś takiego, jak i tak pierwszy lepszy admin któremu podpadł jakiś gracz bo napisał na niego skargę i dostał karę (są takie przypadki, nie będę mówił kto), da mu karę za np. "uderzanie w przydrożne konstrukcje" lub "zabawę holownikiem", pomimo tego że np. nikogo nie było przy tym i nikomu nie przeszkadzało tego co gracz robi sobie w np. SF z autem albo bawi się C-Bugiem.
Mnie to irytuję i innych też, bo admin spectuje kogoś i widzi od razu, że łamie LKiZ ale nikomu nie robi krzywdy to musi dać karę tak czy siak.

**Comment by Mrucznik** [comment]
Odrzucam. To, że nikomu to nie przeszkadza w danej chwili, nie oznacza, że nie przeszkadza to administratorowi. Administrator też człowiek. Po za tym taka definicja zostawiałaby furtkę do łamania LKiZ przez graczy przy adminach, a admin nie mógłby nic z tym zrobić, bo w pobliżu nie byłoby żadnych graczy.
Admin nie powinien postępować tak, jak to opisałeś, lecz to powinno być traktowane indywidualnie i moim zdaniem gorsze naruszenia byłby z powodu wprowadzenia Twojej wersji zasady, niż z obecnej.
