### ISSUE TITLE
Zmiana definicji BBH.

### ISSUE THREAD

**Issue by panpecet** [Mrucznik/Mrucznik-Docs#52]
**Opis zmiany.**
Oryginał: "BMX Bunny Hopping (BBH) - skakanie na BMX'ie po samochodach graczy/graczach (karane na skargę gracza).".
Proponowana: "BMX Bunny Hopping (BBH) - skakanie na rowerze po samochodach graczy/graczach (karane na skargę gracza).".

**Dlaczego uważasz, że zmiana jest potrzebna.**
Nie tylko skakanie konkretnie BMXem powinno być karane, ale innymi rowerami również.

**Comment by skMetinek** [comment]
Jaki jest sens tej kary? Jeżeli już zmieniamy, to polecałbym usunąć karania tylko na prośbę tzn. skargę gracza, bo dochodzi do nadużyć i kończy się przeważnie skargami na adminów którzy karają gracza od buta.

**Comment by Mrucznik** [comment]
<del>BBH zostanie usunięte z LKiZ.
Na BBH należy reagować w sposób IC.</del>

**Comment by Mrucznik** [comment]
Definicja zmieniona
