### ISSUE TITLE
kary za dm są za wysokie

### ISSUE THREAD

**Issue by uzytkownik-github** [Mrucznik/Mrucznik-Docs#8]
Witam, kary za DM powinny być niższe. Bądźmy łagodni.

**Comment by uzytkownik-github** [comment]
jak to za wysokie!!! 900min aj dla każdego dmiarza, to ich nauczy

**Comment by Mrucznik** [comment]
Proponuje obniżenie do 1 sekundy AJ za każdego zabitego gracza. To ich nauczy.
